### ISSUE TITLE
Bug: Kubernetes Pod Spec Command Doesn't Match Dockerfile CMD

### ISSUE THREAD

**Issue by MartiinWalsh** [open-sauced/pizza#12]
### Describe the bug

Hello,

I encountered a problem when trying to deploy the pizza-oven application with Kubernetes. The `command` field in the Kubernetes pod spec uses a relative path (`./pizza-oven`) while the Dockerfile's `CMD` instruction uses an absolute path (`/usr/bin/pizza-oven`).

Pod Spec:
``` yaml
spec:
  containers:
  - name: pizza-oven
    image: pizza-oven:latest
    imagePullPolicy: IfNotPresent
    command:
    - ./pizza-oven
```

Dockerfile:
``` dockerfile
FROM --platform=${TARGETPLATFORM:-linux/amd64} cgr.dev/chainguard/glibc-dynamic
COPY --from=builder /app/pizza-oven /usr/bin/
CMD ["/usr/bin/pizza-oven"]
```

Due to this, the container fails to start up, as it's looking for the executable in the wrong place. I have a change ready to update the pod spec to use the absolute path to match the Dockerfile's CMD instruction.

### Steps to reproduce

run `make setup-test-env`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs
